DROP TABLE IF EXISTS GAME;

CREATE TABLE GAME
(
    ID LONG NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    GENRE VARCHAR(255) NOT NULL,
    STATUS VARCHAR(100) CHECK (STATUS IN ('PUBLISHED', 'UNPUBLISHED'))
);

CREATE INDEX name_idx ON GAME(NAME);